### ISSUE TITLE
Revert 'Master' to 'Legacy'

### ISSUE THREAD

**Issue by sbhadr** [RbxAPI/Pyblox#1]

**Comment by devSparkle** [comment]
Is this a branch reversion? Could you provide some more details?

**Comment by sbhadr** [comment]
Sorry for the confusion. In simple terms, master will be placed in a separate branch called, "Legacy" which is stationary and immune from updates. Master will become the most recent up-to-date version of the lib. As of now, "Legacy" is technically the Python2 & Python3 branches.

**Comment by PizzaCrust** [comment]
stationary and immutable
