### ISSUE TITLE
pyblox module not getting referenced

### ISSUE THREAD

**Issue by 4TH4RV** [RbxAPI/Pyblox#11]
Hey, I am fairly new to python (started yesterday lol ). Sorry if this is too basic. 

I tried installing pyblox3 by the manual method and pip method both, also tried uninstalling and installing again and restarting my IDE. I have python 3+ version and PyCharm as the IDE. It still says "pyblox3 module doesnt exist"

![image](https://user-images.githubusercontent.com/62333550/85219419-25a74280-b3c1-11ea-92b6-d97bca3b358b.png)

What am I doing wrong?

![image](https://user-images.githubusercontent.com/62333550/85219436-57b8a480-b3c1-11ea-989a-b0e680551b94.png)

this is the pyblox3 folder in Python>Lib>Site-Packages> pyblox3

**Comment by Pythonic-Rainbow** [comment]
Do you have multiple Python interpreters installed?

**Comment by 4TH4RV** [comment]
> Do you have multiple Python interpreters installed?

Nope, I have the default interpreter installed.

I solved this issue by going in settings and installing this package, then it worked fine.
