### ISSUE TITLE
Groups - getUserRole no longer functions.

### ISSUE THREAD

**Issue by ThePugi** [RbxAPI/Pyblox#5]
Using getUserRole on the master branch no longer works. I get an HTTP Error 410 (gone). Attempting to visit the link tells me it was removed.

https://www.roblox.com/Game/LuaWebService/HandleSocialRequest.ashx?method=GetGroupRole&playerid=113754334&groupId=3017674

> ERROR:root:[Pyblox][GET] Something went wrong. Error: 410
None

**Comment by iranathan** [comment]
Yes the endpoint was deleted.

**Comment by sbhadr** [comment]
Addressed in https://github.com/RbxAPI/Pyblox/commit/437fe9efaf4cf4d8632cccc0ad2bd509d46a7081
