### ISSUE TITLE
How do I iterate through the groupList?

### ISSUE THREAD

**Issue by jmkd3v** [RbxAPI/Pyblox#6]
`groups = pyblox3.Groups.groupList(myuseridgoeshere)` does return a list of my groups, but iterating through it gives me what seems like a bunch of unrelated numbers and it seems like a strange type of JSON thing. I just want to get a single group out of it and check my role in that group.

**Comment by sbhadr** [comment]
That's because Python interprets the returned list as a byte string. Byte strings look like this, ``b'content'``. To convert a byte string into a valid ``JSON``, you can do ``json.loads(group)``.

Here's a code example:
```python
from pyblox3 import Groups
import json

# Might want to check if this is None before calling json.loads
groups = json.loads(Groups.groupList(userid))

for group in groups:
  print(group)
```
I'll make this easier in ``v3`` to help make most of this automatic.

**Comment by jmkd3v** [comment]
Thanks a lot.
