### ISSUE TITLE
Refresh cookie endpoint

### ISSUE THREAD

**Issue by iranathan** [RbxAPI/Pyblox#8]
For context: https://github.com/RbxAPI/Pyblox/blob/nightly_build/pyblox3/src/util/req.py#L69

I really don't think this is necessary, It will just respond with an error because your not sending an xcsrf token. Thats why I think your cookie did not refresh. Further the endpoint being used (if it succeeds) will refresh the cookie and send a new one in the response cookies.

Thanks, Ira.

**Comment by sbhadr** [comment]
Discussion & answers were stated in the discord. Closing.
